<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 plaincoin.glb
-->

<script lang='ts'>
  import animation from './coin-animation.json'
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Theatre, Editable, Sheet } from '@threlte/theatre'

  export const ref = new Group()

  const gltf = useGltf('/plaincoin.glb')

  const component = forwardEventHandlers()

</script>

<Theatre config={{ state: animation }} studio={false}>
  <Sheet autoPlay>
  <Editable name="Coin" props={{ scale: 0, opacity: 0, rotation: 0 }} let:values>
  <T is={ref} dispose={false} {...$$restProps} scale={values.scale} rotation.y={values.rotation} bind:this={$component}>
    {#await gltf}
      <slot name="fallback" />
    {:then gltf}
      <T.Mesh
        geometry={gltf.nodes.Curve002.geometry}
        material={gltf.materials['Material.002']}
        material.opacity={values.opacity}
        material.transparent
        material.side={0}
        position={[-1.41, -1.39, 0.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={30.71}
      />
    {:catch error}
      <slot name="error" {error} />
    {/await}
  
    <slot {ref} />
  </T>
  </Editable>
</Sheet>
</Theatre>
