<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 coin.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/coin.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials['Material.002']}
      position={[0, -0.04, -0.28]}
      rotation={[1.27, 0, -0.46]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve001.geometry}
      material={gltf.materials['Material.002']}
      position={[-1.17, -1.11, 0.93]}
      rotation={[1.27, 0, -0.46]}
      scale={30.71}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve002.geometry}
      material={gltf.materials['Material.002']}
      position={[1.17, -1.61, -0.65]}
      rotation={[1.27, 0, 2.68]}
      scale={30.71}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
